### PR TITLE
Add CONTRIBUTING.md

### LINKED ISSUE #13: Add Contributing file
Add the contributing file is useful for new contributors, so they know what to do in this project

Here's a reference link: [Contributing.md](https://mozillascience.github.io/working-open-workshop/contributing/)

### PR DESCRIPTION
**Pull request by LJNeon**
Let me know if there are any adjustments you want made, I took inspiration from some simpler repositories.

closes #13

### CODE REVIEW

**Comment by Hoekstraa** [comment]
Here's a few more thoughts on it;
(Thanks thusfar, your input is triggering me to think about it more)

Asking questions in Issues is fine too, if you don't have Discord.
I wouldn't want Discord to be a requirement for working on the project.

How would one check if someone's worked on something?
And what then?
Let's say someone mentioned started working on issue #xyx 2 weeks ago, but hasn't delivered yet? 

The note about OS, environment etc. is a good call.

After I merge @HeinousTugboat's PRs, you could add a little about how to build the project.
e.g. pull it, build and run it, do the tests locally, run the formatter/linter, and PR.

**Comment by LJNeon** [comment]
> Asking questions in Issues is fine too, if you don't have Discord.

The discord comment was under pull requests, not for issues. Does that change anything or should I still change it to just a note that the discord channel exists?

> How would one check if someone's worked on something?

I guess my thought was asking on discord or looking for an open PR that's not dead. I can remove that line if you'd like.

> e.g. pull it, build and run it, do the tests locally, run the formatter/linter, and PR.

Should I just do that now with the thought that @HeinousTugboat's PRs will be merged fairly soon?

**Comment by Hoekstraa** [comment]
> The discord comment was under pull requests, not for issues. Does that change anything or should I still change it to just a note that the discord channel exists?

Currently it reads as if it's a requirement. Softening the language more towards 'feel free to pop in at the Discord to ask for help or clarification on anything related to this project' or something alike, would be preferable.

> I guess my thought was asking on discord or looking for an open PR that's not dead. I can remove that line if you'd like.

I think it's fair to say 'check if someone else hasn't recently said they've taken up an issue'.
Again, no Discord, just as a comment in this repo.

> Should I just do that now with the thought that @HeinousTugboat's PRs will be merged fairly soon?

Just merged them. So yes.

**Comment by LJNeon** [comment]
Just pushed an update, let me know if it looks good or if you want additional changes.

**Pull request merged**
