### PR TITLE
chore: add eslint

### LINKED ISSUE #6: Add linting
A linter for the code would be very nice to have.
You don't necessarily have to fix all linting issues within the PR adding the linter.
But you do have to add it to the package.json as a `npm run lint` option.

### PR DESCRIPTION
**Pull request by Dun-sin**
## Changes proposed
- add eslint

### CODE REVIEW

**Review by Hoekstraa — APPROVED** [review]
Nice, will merge the package changes soon!

**Comment by LJNeon** [comment]
Looks like this doesn't account for the recently merged typescript PR, and it also has merge conflicts because it actually lints the files.

**Comment by Dun-sin** [comment]
> Looks like this doesn't account for the recently merged typescript PR, and it also has merge conflicts because it actually lints the files.

This PR isn't merged yet I don't see how it affects things

**Comment by Hoekstraa** [comment]
Oh, my bad, yeah, TS requires some extra packages apparently.
I marked it with the accepted label and gave it a positive review, so if Hacktober is important to you, it still counts.
You did exactly as requested, but I'm gonna close it due to not matching up with the repo's current state.

If you want, you can make another PR with changes that are compatible with the current state and I'll promise to merge it on the spot if it checks out. But I totally understand if you don't.

I'm very sorry!

**Comment by Dun-sin** [comment]
> Oh, my bad, yeah, TS requires some extra packages apparently.
> I marked it with the accepted label and gave it a positive review, so if Hacktober is important to you, it still counts.
> You did exactly as requested, but I'm gonna close it due to not matching up with the repo's current state.
> 
> If you want, you can make another PR with changes that are compatible with the current state and I'll promise to merge it on the spot if it checks out. But I totally understand if you don't.
> 
> I'm very sorry!
> 

I have enough points for Hacktoberfest, I was doing this because I normally contribute to open source before Hacktober.

Can you explain what you really need?

**Pull request closed without merging**
